/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TicketBooking;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;


public class App extends Application{
    public static Stage primaryStage;
    @Override
    public void start(Stage stage) throws Exception {
        primaryStage = stage;
        FXMLLoader loader = new FXMLLoader();
        loader.setLocation(getClass().getResource("/view/LoginStage.fxml"));
        Parent root = loader.load();

        stage.setTitle("TicketBookingSystem");
        stage.setScene(new Scene(root));
        stage.setResizable(false);
        stage.show();

    }

    public static Stage getStage() {
        return primaryStage;
    }

    public static void main(String[] args) {
        //Validator validator = new ValidatorImpl();
        launch(args);


    }

}
